#!/bin/bash
# Define somme colors to use in script

COLOR_NC='\e[0m' # No Color
COLOR_WHITE='\e[1;37m'
COLOR_BLACK='\e[0;30m'
COLOR_BLUE='\e[0;34m'
COLOR_LIGHT_BLUE='\e[1;34m'
COLOR_GREEN='\e[0;32m'
COLOR_LIGHT_GREEN='\e[1;32m'
COLOR_CYAN='\e[0;36m'
COLOR_LIGHT_CYAN='\e[1;36m'
COLOR_RED='\e[0;31m'
COLOR_LIGHT_RED='\e[1;31m'
COLOR_PURPLE='\e[0;35m'
COLOR_LIGHT_PURPLE='\e[1;35m'
COLOR_BROWN='\e[0;33m'
COLOR_YELLOW='\e[1;33m'
COLOR_GRAY='\e[0;30m'
COLOR_LIGHT_GRAY='\e[0;37m'

#    tput setab [1-7] – Set a background color using ANSI escape
#    tput setb [1-7] – Set a background color
#    tput setaf [1-7] – Set a foreground color using ANSI escape
#    tput setf [1-7] – Set a foreground color
#
#    tput bold – Set bold mode
#    tput dim – turn on half-bright mode
#    tput smul – begin underline mode
#    tput rmul – exit underline mode
#    tput rev – Turn on reverse mode
#    tput smso – Enter standout mode (bold on rxvt)
#    tput rmso – Exit standout mode


C_NC=$(tput sgr0)

C_BLACK=$(tput setaf 0)
C_RED=$(tput setaf 1)
C_GREEN=$(tput setaf 2)
C_YELLOW=$(tput setaf 3)
C_BLUE=$(tput setaf 4)
C_MAGENTA=$(tput setaf 5)
C_CYAN=$(tput setaf 6)
C_WHITE=$(tput setaf 7)

C_B_BLACK=$(tput bold)$(tput setaf 0)
C_B_RED=$(tput bold)$(tput setaf 1)
C_B_GREEN=$(tput bold)$(tput setaf 2)
C_B_YELLOW=$(tput bold)$(tput setaf 3)
C_B_BLUE=$(tput bold)$(tput setaf 4)
C_B_MAGENTA=$(tput bold)$(tput setaf 5)
C_B_CYAN=$(tput bold)$(tput setaf 6)
C_B_WHITE=$(tput bold)$(tput setaf 7)

C_U_BLACK=$(tput sgr 0 1)$(tput setaf 0)
C_U_RED=$(tput sgr 0 1)$(tput setaf 1)
C_U_GREEN=$(tput sgr 0 1)$(tput setaf 2)
C_U_YELLOW=$(tput sgr 0 1)$(tput setaf 3)
C_U_BLUE=$(tput sgr 0 1)$(tput setaf 4)
C_U_MAGENTA=$(tput sgr 0 1)$(tput setaf 5)
C_U_CYAN=$(tput sgr 0 1)$(tput setaf 6)
C_U_WHITE=$(tput sgr 0 1)$(tput setaf 7)

C_BU_BLACK=$(tput bold)$(tput sgr 0 1)$(tput setaf 0)
C_BU_RED=$(tput bold)$(tput sgr 0 1)$(tput setaf 1)
C_BU_GREEN=$(tput bold)$(tput sgr 0 1)$(tput setaf 2)
C_BU_YELLOW=$(tput bold)$(tput sgr 0 1)$(tput setaf 3)
C_BU_BLUE=$(tput bold)$(tput sgr 0 1)$(tput setaf 4)
C_BU_MAGENTA=$(tput bold)$(tput sgr 0 1)$(tput setaf 5)
C_BU_CYAN=$(tput bold)$(tput sgr 0 1)$(tput setaf 6)
C_BU_WHITE=$(tput bold)$(tput sgr 0 1)$(tput setaf 7)

C_REVERSE=$(tput rev)

red='\e[0;31m'
RED='\e[1;31m'

green='\e[0;32m'
GREEN='\e[1;32m'

yello='\e[0;33m'
YELLOW='\e[1;33m'

blue='\e[0;34m'
BLUE='\e[1;34m'

violet='\e[0;35m'
VIOLET='\e[01;35m'

cyan='\e[0;36m'
CYAN='\e[1;36m'

white='\e[0;37m'
WHITE='\e[1;37m'

ul='\e[4m'
UL='\e[1;4m'

NC='\e[0m'			# No color

# For prompt
head_line='\e[01;36m'
